language: ruby
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
matrix:
  include:
  - rvm: 2.2.6
    env: PUPPET_VERSION='~> 4.7.0'
    script: bundle exec rake test
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=centos7 BEAKER_debug=true
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=jessie BEAKER_debug=true
    script: bundle exec rake beaker
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set=xenial BEAKER_debug=true
    script: bundle exec rake beaker
